# Generated by Django 6.0.5 on 2026-07-03 12:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('pharmacy', '0002_alter_stockmovement_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPENDENT', 'Dependent'), ('EXTERNAL', 'External / Villager')], default='EXTERNAL', max_length=20)),
                ('external_patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='beneficiaries.dependent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='beneficiaries.employee')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='pharmacy.medicalcenter')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
