# Generated by Django 6.0.5 on 2026-06-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='post_name',
            new_name='post_nom',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='prenom',
        ),
    ]
