# Generated by Django 6.0.5 on 2026-07-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('pharmacy', '0002_alter_stockmovement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation'),
        ),
    ]
